src/ASEAPROJECT.Web.Mvc/Controllers/ExternalRolesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASEAPROJECT.Controllers;
using ASEAPROJECT.Services.ExternalRoleService;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Extensions;
using ASEAPROJECT.Dtos.ExternalRoles;

namespace ASEAPROJECT.Web.Mvc.Controllers
{
    public class ExternalRolesController : ASEAPROJECTControllerBase
    {
        private readonly IExternalRoleService _rolesService;

        public ExternalRolesController(IExternalRoleService roleService)
        {
            _rolesService = roleService;
        }

        // GET: ExternalRoles
        public async Task<IActionResult> Index()
        {
            var roles = (await _rolesService.GetAll(new PagedAndSortedResultRequestDto())).Items;
            return View(roles);
        }


        // GET: ExternalRoles/Create
        public IActionResult Create()
        {
            if (Request.IsAjaxRequest())
                return PartialView("Create");
            else
                return View("Create");
        }

        // POST: ExternalRoles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExternalRoleDto role)
        {
            if (ModelState.ErrorCount == 0)
            {
                await _rolesService.Create(role);
                if (Request.IsAjaxRequest())
                    return Content("OK");
                else
                    return RedirectToAction("Index");
            }
            if (Request.IsAjaxRequest())
                return PartialView("Create", role);
            else
                return View("Create", role);
        }

        // GET: ExternalRoles/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _rolesService.Get(id);
            if (Request.IsAjaxRequest())
                return PartialView(model);
            else
                return View(model);
        }

        // POST: ExternalRoles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ExternalRoleDto role)
        {
            if (ModelState.ErrorCount == 0)
            {
                await _rolesService.Update(role);
                if (Request.IsAjaxRequest())
                    return Content("OK");
                else
                    return RedirectToAction("Index");
            }

            if (Request.IsAjaxRequest())
                return PartialView("Edit", role);
            else
                return View("Edit", role);
        }


        // POST: ExternalRoles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _rolesService.Get(id);
            var result = _rolesService.Delete(model);

            return new JsonResult(new { success = true, data = result });
        }
    }
}

src/ASEAPROJECT.Web.Mvc/Views/ExternalRoles/Create.cshtml
@model ASEAPROJECT.Dtos.ExternalRoles.ExternalRoleDto

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="ExternalRoles" asp-for="Id" id="paramForm">
            <h2>@L("Create")</h2>

            <div id="form-fields">
                @await Html.PartialAsync("_Form")
            </div>
        </form>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/ExternalRoles/Edit.cshtml
@model ASEAPROJECT.Dtos.ExternalRoles.ExternalRoleDto
@{
    ViewData["Title"] = "Edit";
}



<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="ExternalRoles" asp-for="Id" id="paramForm">
            <h2>@L("Edit")</h2>
            <input type="hidden" asp-for="Id" />
            <div id="form-fields">
                @await Html.PartialAsync("_Form");
            </div>
        </form>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/ExternalRoles/Index.cshtml
@model IEnumerable<ASEAPROJECT.Dtos.ExternalRoles.ExternalRoleDto>

@{
    ViewData["Title"] = "Index";
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @L("Events")
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block">
                                    <i class="material-icons">refresh</i>Refresh
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@L("Name")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var externalRoleDto in Model)
                        {
                            <tr>
                                <td>@externalRoleDto.name</td>
                                <td class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">menu</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="#" class="waves-effect waves-block edit-externalRoleDto" data-externalRoleDto-id="@externalRoleDto.Id"
                                               data-toggle="modal" data-target="#dialog" data-action="ExternalRoles/Edit?id=@externalRoleDto.Id">
                                                <i class="material-icons">edit</i>@L("Edit")
                                            </a>
                                        </li>
                                        <li>
                                            <a id="delete" url="/ExternalRoles/Delete" class="waves-effect waves-block delete-externalRoleDto" data-Dto-id="@externalRoleDto.Id">
                                                <i class="material-icons">delete_sweep</i>@L("Delete")
                                            </a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <button type="button" class="btn btn-primary btn-circle waves-effect waves-circle waves-float pull-right" data-toggle="modal"
                        data-target="#dialog" data-action="/ExternalRoles/Create">
                    <i class="material-icons">add</i>
                </button>
            </div>
        </div>
    </div>
</div>


<div>
    @await Html.PartialAsync("Modals/_Modal")
</div>

src/ASEAPROJECT.Web.Mvc/Views/ExternalRoles/_Form.cshtml
@model ASEAPROJECT.Dtos.ExternalRoles.ExternalRoleDto
<div asp-validation-summary="All" class="alert"></div>
<br />
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label asp-for="name">@L("Name")</label>
            <input class="form-control" asp-for="name" />
        </div>
    </div>
</div>