src/ASEAPROJECT.Web.Mvc/Controllers/MensBathroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Extensions;
using ASEAPROJECT.Controllers;
using ASEAPROJECT.Dtos.MensBathrooms;
using ASEAPROJECT.Services.MensBathroomService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ASEAPROJECT.Web.Mvc.Controllers
{
    public class MensBathroomController : ASEAPROJECTControllerBase
    {
        private readonly IMensBathroomService _itemService;

        public MensBathroomController(IMensBathroomService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> Index()
        {
            var items = (await _itemService.GetAll(new PagedAndSortedResultRequestDto())).Items;
            return View(items);
        }


        public IActionResult Create()
        {
            if (Request.IsAjaxRequest())
                return PartialView("Create");
            else
                return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MensBathroomDto item)
        {
            if (ModelState.ErrorCount == 0)
            {
                await _itemService.Create(item);
                if (Request.IsAjaxRequest())
                    return Content("OK");
                else
                    return RedirectToAction("Index");
            }
            if (Request.IsAjaxRequest())
                return PartialView("Create", item);
            else
                return View("Create", item);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await _itemService.Get(id);
            if (Request.IsAjaxRequest())
                return PartialView(model);
            else
                return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MensBathroomDto item)
        {
            if (ModelState.ErrorCount == 0)
            {
                await _itemService.Update(item);
                if (Request.IsAjaxRequest())
                    return Content("OK");
                else
                    return RedirectToAction("Index");
            }

            if (Request.IsAjaxRequest())
                return PartialView("Edit", item);
            else
                return View("Edit", item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _itemService.Get(id);
            var result = _itemService.Delete(model);

            return new JsonResult(new { success = true, data = result });
        }
    }
}

src/ASEAPROJECT.Web.Mvc/Views/MensBathroom/Create.cshtml
@model ASEAPROJECT.Dtos.MensBathrooms.MensBathroomDto
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="MensBathroom" asp-for="Id" id="paramForm">
            <h2>@L("Create")</h2>

            <div id="form-fields">
                @await Html.PartialAsync("_Form")
            </div>
        </form>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/MensBathroom/Edit.cshtml
@model ASEAPROJECT.Dtos.MensBathrooms.MensBathroomDto

@{
    ViewData["Title"] = "Edit";
}



<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="MensBathroom" asp-for="Id" id="paramForm">
            <h2>@L("Edit")</h2>
            <input type="hidden" asp-for="Id" />
            <div id="form-fields">
                @await Html.PartialAsync("_Form");
            </div>
        </form>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/MensBathroom/Index.cshtml
@model IEnumerable<ASEAPROJECT.Dtos.MensBathrooms.MensBathroomDto>

@{
    ViewData["Title"] = "Index";
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @L("MensBathroom")
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block">
                                    <i class="material-icons">refresh</i>Refresh
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@L("Name")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var eventDto in Model)
                        {
                            <tr>
                                <td>@eventDto.name</td>
                                <td class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">menu</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="#" class="waves-effect waves-block edit-itemDto" data-eventDto-id="@eventDto.Id"
                                               data-toggle="modal" data-target="#dialog" data-action="MensBathroom/Edit?id=@eventDto.Id">
                                                <i class="material-icons">edit</i>@L("Edit")
                                            </a>
                                        </li>
                                        <li>
                                            <a id="delete" url="/MensBathroom/Delete" class="waves-effect waves-block delete-eventDto" data-Dto-id="@eventDto.Id">
                                                <i class="material-icons">delete_sweep</i>@L("Delete")
                                            </a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <button type="button" class="btn btn-primary btn-circle waves-effect waves-circle waves-float pull-right" data-toggle="modal"
                        data-target="#dialog" data-action="/MensBathroom/Create">
                    <i class="material-icons">add</i>
                </button>
            </div>
        </div>
    </div>
</div>


<div>
    @await Html.PartialAsync("Modals/_Modal")
</div>

src/ASEAPROJECT.Web.Mvc/Views/MensBathroom/_Form.cshtml
@model ASEAPROJECT.Dtos.MensBathrooms.MensBathroomDto

<div asp-validation-summary="All" class="alert"></div>
<br />
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label asp-for="name">@L("Name")</label>
            <input class="form-control" asp-for="name" />
        </div>
    </div>
</div>