src/ASEAPROJECT.Web.Mvc/Controllers/ResidualLogsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASEAPROJECT.Controllers;
using ASEAPROJECT.Services.ResidualLogService;
using ASEAPROJECT.Services.ExternalFirmService;
using ASEAPROJECT.Services.EquipItemService;
using Abp.Application.Services.Dto;
using ASEAPROJECT.Dtos.ResidualLogs;
using Abp.AspNetCore.Mvc.Extensions;
using Rotativa.AspNetCore;
using System.Collections.Generic;
using ASEAPROJECT.Entities;
using AutoMapper;
using ASEAPROJECT.Services.EquipLogService;
using ASEAPROJECT.Services.TemporqaryStorageService;

namespace ASEAPROJECT.Web.Mvc.Controllers
{
    public class ResidualLogsController : ASEAPROJECTControllerBase
    {
        private readonly IResidualLogService _residualLogService;
        private readonly IExternalFirmService _externalFirmService;
        private readonly IEquipItemService _equipItemService;
        private readonly IEquipLogService _equipLogService;
        private readonly ITemporaryStorageService _temporaryStorageService;


        public ResidualLogsController(IResidualLogService residualLogService,
            IExternalFirmService externalFirmService, IEquipItemService equipItemService,
            IEquipLogService equipLogService, ITemporaryStorageService temporaryStorageService)
        {
            _residualLogService = residualLogService;
            _externalFirmService = externalFirmService;
            _equipItemService = equipItemService;
            _equipLogService = equipLogService;
            _temporaryStorageService = temporaryStorageService;
        }


        // GET: ResidualLogs
        public async Task<IActionResult> Index()
        {
            var logs = (await _residualLogService.GetAll(new PagedAndSortedResultRequestDto())).Items;
            return View(logs);
        }


        // GET: ResidualLogs/Create
        public async Task<IActionResult> Create()
        {
            var model = new ResidualLogDto();
            model.equipment = new List<EquipLog>();
            await setViewBag();
            return View(model);
        }

        private async Task setViewBag()
        {
            ViewBag.items = (await _equipItemService.GetAll(new PagedAndSortedResultRequestDto())).Items;
            ViewBag.extraccion = (await _externalFirmService.GetAllwithroles()).Where(r=> r.roles.Any(e => e.role.name == "Extraccion"));
            ViewBag.transporte = (await _externalFirmService.GetAllwithroles()).Where(r => r.roles.Any(e => e.role.name == "Transporte"));
            ViewBag.Recepcion = (await _externalFirmService.GetAllwithroles()).Where(r => r.roles.Any(e => e.role.name == "Recepcion"));
            ViewBag.storages = (await _externalFirmService.GetAllwithroles()).Where(r => r.roles.Any(e => e.role.name == "Almacenamiento"));
        }

        // POST: ResidualLogs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ResidualLogDto log, List<int> equipment = null)
        {
            if (ModelState.ErrorCount == 0)
            {
                log.equipment = new List<EquipLog>();
                foreach(var equip in equipment)
                {
                    log.equipment.Add(new EquipLog() { residual_log_id = log.Id, equip_id = equip });
                }
                await _residualLogService.Create(log);
                return RedirectToAction("Index");
            }
            return View("Create", log);
        }

        // GET: ResidualLogs/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            await setViewBag();
            var model = await _residualLogService.Get(id);
            model.equipment = Mapper.Map<List<EquipLog>>(_equipLogService.GetAllByLog(id));
            return View(model);
        }

        // POST: ResidualLogs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ResidualLogDto log, List<int> equipment = null)
        {
            if (ModelState.ErrorCount == 0)
            {
                log.equipment = new List<EquipLog>();
                foreach (var equip in equipment)
                {
                    log.equipment.Add(new EquipLog() { residual_log_id = log.Id, equip_id = equip });
                }
                await _residualLogService.Update(log);
                if (Request.IsAjaxRequest())
                    return Content("OK");
                else
                    return RedirectToAction("Index");
            }

            if (Request.IsAjaxRequest())
                return PartialView("Edit", log);
            else
                return View("Edit", log);
        }

        // POST: ResidualLogs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _residualLogService.Get(id);
            var result = _residualLogService.Delete(model);

            return new JsonResult(new { success = true, data = result });
        }

        public async Task<IActionResult> toPdf(int id)
        {
            var model = await _residualLogService.Get(id);
            return new ViewAsPdf("ResidualAsPdf",model);
        }
    }
}

src/ASEAPROJECT.Web.Mvc/Views/ResidualLogs/Create.cshtml
@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-md-9">
        <form asp-action="Create" asp-controller="ResidualLogs">
            <h2>@L("Create")</h2>
            <div id="form-fields">
                @await Html.PartialAsync("_Form")
            </div>
            <a asp-action="Index" class="btn btn-danger">@L("back")</a>
            <input name="create" type="submit" class="btn btn-primary" value="@L("Save")" />
        </form>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/ResidualLogs/Edit.cshtml
@model ASEAPROJECT.Dtos.ResidualLogs.ResidualLogDto


<div class="row">
    <div class="col-md-9">
        <form asp-action="Edit" asp-controller="ResidualLogs">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h2>@L("Edit")</h2>
            <input type="hidden" asp-for="Id" />

            <div id="form-fields">
                @await Html.PartialAsync("_Form")
            </div>
           

            <a asp-action="Index" class="btn btn-danger">@L("back")</a>
            <input type="submit" value="@L("Save")" class="btn btn-primary" />
        </form>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/ResidualLogs/Index.cshtml
@model IEnumerable<ASEAPROJECT.Dtos.ResidualLogs.ResidualLogDto>

@{
    ViewData["Title"] = "Index";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    @L("ResidualLogs")
                </h2>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a id="RefreshButton" href="javascript:void(0);" class="waves-effect waves-block">
                                    <i class="material-icons">refresh</i>Refresh
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@L("Certification_Number")</th>
                            <th>@L("Emission_date")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var logDto in Model)
                        {
                            <tr>
                                <td>@logDto.certnumber</td>
                                <td>@logDto.emissiondate</td>
                                <td class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">menu</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a title="@L("Edit")" name="edit" asp-action="Edit" asp-controller="ResidualLogs"
                                               asp-route-id="@logDto.Id">
                                                <i class="material-icons">edit</i>@L("Edit")
                                            </a>
                                        </li>
                                        <li>
                                            <a id="delete" url="/ResidualLogs/Delete" class="waves-effect waves-block delete-logDto" data-Dto-id="@logDto.Id">
                                                <i class="material-icons">delete_sweep</i>@L("Delete")
                                            </a>
                                        </li>
                                        <li>
                                            <a id="toPdf" href="/ResidualLogs/toPdf/@logDto.Id" class="waves-effect waves-block toPdf-logDto" target="_blank" data-Dto-id="@logDto.Id">
                                                <i class="material-icons">assignment_returned</i>@L("toPDF")
                                            </a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <input name="create-new" class="btn btn-primary pull-right" type="button" value="@L("createNew")" onclick="location.href='@Url.Action("Create","ResidualLogs")'" />
            </div>
        </div>
    </div>
</div>

src/ASEAPROJECT.Web.Mvc/Views/ResidualLogs/ResidualAsPdf.cshtml
@model ASEAPROJECT.Dtos.ResidualLogs.ResidualLogDto
@{
    Layout = null;
}

<html>
<head>
    <meta charset="utf-8">
    <title>Demo</title>
    <link rel="license" href="https://www.opensource.org/licenses/mit-license/">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/src/jquery.js"></script>
</head>
<body>
</body>
</html>  

src/ASEAPROJECT.Web.Mvc/Views/ResidualLogs/_Form.cshtml
@model ASEAPROJECT.Dtos.ResidualLogs.ResidualLogDto

<div asp-validation-summary="All" class="alert"></div>
<br />

<div class="row">
    <div class=" col-md-6">
        <div class="form-inline">
            <label class="control-label">@L("ResidueType"):</label>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" asp-for="residueType" value="Peligroso">
                <label class="form-check-label" for="residueType">@L("Danger")</label>
            </div>

            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" asp-for="residueType" value="No Peligroso">
                <label class="form-check-label" for="residueType">@L("Nodanger")</label>
            </div>
        </div>
    </div>

    <div class=" col-md-6">
        <div class="form-inline">
            <label>@L("Personalauth"):</label>
                <div class="form-check form-check-inline">
                    <input asp-for="personalAuth" type="radio" value='1' />
                    <label class="form-check-label" for="personalAuth">@L("Yes")</label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="personalAuth" type="radio" value='0' />
                    <label class="form-check-label" for="personalAuth">@L("No")</label>
                </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class=" col-md-6">
        <div class="form-group">
            <label asp-for="civilpermission" class="control-label">@L("Civilpermission")</label>
            <input asp-for="civilpermission" class="form-control" />
            <span asp-validation-for="civilpermission" class="text-danger"></span>
        </div>
    </div>

    <div class=" col-md-6">
        <div class="form-group">
            <label asp-for="temp_storage_id" class="control-label">@L("Tempsavage")</label>
            <select asp-for="temp_storage_id" class="form-control">
                <option>Chose one option</option>
                @foreach (var storage in ViewBag.storages)
                {
                    <option value="@storage.Id" selected="@(Model.temp_storage_id == storage.Id)">@storage.name</option>
                }
            </select>
            <span asp-validation-for="temp_storage_id" class="text-danger"></span>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="certnumber" class="control-label">@L("Certnumber")</label>
            <input asp-for="certnumber" class="form-control" />
            <span asp-validation-for="certnumber" class="text-danger"></span>
        </div>
    </div>

    <div class=" col-md-3">
        <div class="form-group">
            <label asp-for="manifestnumber" class="control-label">@L("Manifestnumber")</label>
            <input asp-for="manifestnumber" class="form-control" />
            <span asp-validation-for="manifestnumber" class="text-danger"></span>
        </div>
    </div>

    <div class=" col-md-3">
        <div class="form-group">
            <label asp-for="emissiondate" class="control-label">@L("Emissiondate")</label>
            <input asp-for="emissiondate" type="date" class="form-control" />
            <span asp-validation-for="emissiondate" class="text-danger"></span>
        </div>
    </div>
</div>

<div class="row">
    <div class=" col-md-6">
        <label asp-for="solidrests" class="control-label">@L("Solidrests")</label>
        <div class="input-group">
            <input type="number" asp-for="solidrests" class="form-control" />
            <div class="input-group-append">
                <span class="input-group-text">Kg</span>
            </div>
        </div>
    </div>

    <div class=" col-md-6">
        <label asp-for="liquidrests" class="control-label">@L("Liquidrests")</label>
        <div class="input-group">
            <input type="number" asp-for="liquidrests" class="form-control" />
            <div class="input-group-append">
                <span class="input-group-text">Lt</span>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class=" col-md-6">
        <label>@L("Equipment")</label>
        <div class="input-group">
            @foreach (var item in ViewBag.items)
            {
                <div class="form-check checkbox">
                    <input class="form-check-input" type="checkbox" value="@item.Id" id="defaultCheck1" checked="@(Model.equipment.Any(e => e.equip_id == item.Id))">
                    <label class="form-check-label" for="defaultCheck1">
                        @item.name
                    </label>
                </div>
            }
        </div>
        </div>
    </div>


    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>@L("Name")</th>
                    <th>@L("Firm")</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@("Extraccion")</td>
                    <td>
                        <select asp-for="extraction_firm_id" class="form-control">
                            @foreach (var option in ViewBag.extraccion)
                            {
                                <option value="@option.Id" selected="@(Model.extraction_firm_id == option.Id )">@option.tradename</option>

                            }
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>@L("Transporte")</td>
                    <td>
                        <select asp-for="shipping_firm_id" class="form-control">
                            @foreach (var option in ViewBag.transporte)
                            {
                                <option value="@option.Id" selected="@(Model.shipping_firm_id == option.Id )">@option.tradename</option>

                            }
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>@L("recepcion")</td>
                    <td>
                        <select asp-for="reception_firm_id" class="form-control">
                            @foreach (var option in ViewBag.Recepcion)
                            {
                                <option value="@option.Id" selected="@(Model.reception_firm_id == option.Id )">@option.tradename</option>
                            }
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="row">
        <label asp-for="comments">@L("comments")</label>
        <textarea asp-for="comments" class="form-control"></textarea>
    </div>